# Site settings
title: Causeway
email: dostrenko@lsu.edu
url: https://fredeerock.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/causeway-web"

# Color settings
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: LSU @lab

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/fredeerock
  - title: github
    url: https://github.com/fredeerock/causeway-web

# Build settings
markdown: kramdown
permalink: pretty
